# Generated by Django 4.2.1 on 2023-05-15 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagesFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageTitle', models.CharField(max_length=255)),
                ('expireDate', models.DateTimeField(blank=True, null=True)),
                ('fullText', models.TextField()),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landApp.userprofile')),
            ],
        ),
    ]
