# Generated by Django 4.2.1 on 2023-05-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landApp', '0002_messagesfor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagesfor',
            name='expireDate',
        ),
        migrations.AddField(
            model_name='messagesfor',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
