# Generated by Django 4.2.2 on 2023-06-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landApp', '0003_remove_messagesfor_expiredate_messagesfor_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borderregistration',
            name='remainTime',
        ),
    ]
