# Generated by Django 4.2.2 on 2023-06-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landApp', '0004_remove_borderregistration_remaintime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borderregistration',
            name='products',
        ),
        migrations.AddField(
            model_name='borderregistration',
            name='userProducts',
            field=models.ManyToManyField(blank=True, null=True, to='landApp.product'),
        ),
    ]
