# Generated by Django 4.2.2 on 2023-06-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landApp', '0006_product_description_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportTitle', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, null=True)),
                ('datetime', models.DateField(auto_now=True)),
            ],
        ),
    ]
