# Generated by Django 4.2.2 on 2023-07-04 13:45

from django.db import migrations, models
import landApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('landApp', '0008_borderregistration_fromcountry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borderregistration',
            name='expireDate',
            field=models.DateTimeField(default=landApp.models.three_month_from_today),
        ),
        migrations.AlterField(
            model_name='borderregistration',
            name='porderGeneratedId',
            field=models.CharField(default='borderId_1333', max_length=255),
        ),
    ]
