# Generated by Django 4.2.2 on 2023-07-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landApp', '0009_alter_borderregistration_expiredate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borderregistration',
            name='porderGeneratedId',
            field=models.CharField(default='borderId_5180', max_length=255),
        ),
    ]
