# Generated by Django 4.2.2 on 2023-07-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landApp', '0010_alter_borderregistration_pordergeneratedid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borderregistration',
            name='porderGeneratedId',
            field=models.CharField(default='borderId_3', max_length=255),
        ),
    ]
