# Generated by Django 4.2.2 on 2023-07-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landApp', '0011_alter_borderregistration_pordergeneratedid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borderregistration',
            name='fromCountry',
            field=models.CharField(choices=[('somalia', 'SOMALIA'), ('united state', 'UNITED STATE'), ('kenya', 'KENYA'), ('united state', 'UNITED STATE'), ('united state', 'UNITED STATE'), ('united state', 'UNITED STATE'), ('united state', 'UNITED STATE'), ('united state', 'UNITED STATE')], default='somalia', max_length=255),
        ),
    ]
