# Generated by Django 4.2.2 on 2023-08-14 05:07

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorderRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borderGeneratedId', models.CharField(default='0', max_length=255)),
                ('userLandedType', models.CharField(choices=[('By Flight', 'By Flight'), ('By Train', 'By Train'), ('By Bus', 'By Bus')], default='By Flight', max_length=255)),
                ('borderCurrentState', models.CharField(choices=[('In', 'In The Country Flight'), ('Out', 'Out The Country')], default='In', max_length=255)),
                ('enteringDate', models.DateTimeField()),
                ('idCardNo', models.CharField(max_length=255)),
                ('expireDate', models.DateTimeField(blank=True, default=api.models.three_month_from_today, null=True)),
                ('userAddress', models.CharField(max_length=555)),
                ('nationality', models.CharField(choices=[('Somalia', 'Somalia'), ('Somali-Land', 'Somali-Land'), ('Kenya', 'Kenya '), ('Angola', 'Angola'), ('Italy', 'Italy')], default='Somalia', max_length=255)),
                ('registrationDate', models.DateTimeField(auto_now=True)),
                ('reasonFor', models.CharField(choices=[('Medical', 'Medical'), ('Tourisim', 'Tourisim'), ('Education', 'Education')], default='Education', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FingerPrintScanDt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerPrintCode', models.TextField(blank=True, null=True)),
                ('fingerPrintImage', models.FileField(blank=True, default='fingerprint.jpg', null=True, upload_to='scannedFingers/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ReportInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportTitle', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, null=True)),
                ('datetime', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScannedFaceDt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageName', models.CharField(max_length=255)),
                ('scannedImage', models.FileField(blank=True, null=True, upload_to='scannedImage/')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(default='12345', max_length=255)),
                ('is_superuser', models.BooleanField(default=False)),
                ('passportID', models.CharField(default='PSS-D12', max_length=255)),
                ('fullName', models.CharField(default='', max_length=255)),
                ('gender', models.CharField(default='Male', max_length=255)),
                ('faceDetected', models.FileField(blank=True, null=True, upload_to='usersFaceDetected/')),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to='borderImages/')),
                ('userType', models.CharField(default='Normal User', max_length=255)),
                ('number', models.CharField(default='252', max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('theUser', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessagesFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageTitle', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
                ('fullText', models.TextField()),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Fines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fineTitle', models.CharField(max_length=255)),
                ('fineDesc', models.TextField()),
                ('finePrice', models.IntegerField(default=20)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('fixed', models.BooleanField(default=False)),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=50)),
                ('extraDays', models.IntegerField(default=15)),
                ('reasonForExtraDays', models.CharField(max_length=2555)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('borderingSt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.borderregistration')),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='borderregistration',
            name='theUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile'),
        ),
    ]
