# Generated by Django 4.2.2 on 2023-07-22 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ReportInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportTitle', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, null=True)),
                ('datetime', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(default='', max_length=255)),
                ('faceDetected', models.FileField(blank=True, null=True, upload_to='usersFaceDetected/')),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to='borderImages/')),
                ('userType', models.CharField(default='Normal User', max_length=255)),
                ('number', models.CharField(default='252', max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('theUser', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessagesFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageTitle', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
                ('fullText', models.TextField()),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BorderRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borderGeneratedId', models.CharField(default='0', max_length=255)),
                ('idCardNo', models.CharField(max_length=255)),
                ('expireDate', models.DateTimeField(blank=True, null=True)),
                ('userState', models.CharField(max_length=255)),
                ('userAddress', models.CharField(max_length=555)),
                ('enteringDate', models.DateTimeField()),
                ('nationality', models.CharField(max_length=255)),
                ('fingerPrintCD', models.CharField(default='', max_length=10000)),
                ('registrationDate', models.DateTimeField(auto_now=True)),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
                ('userProducts', models.ManyToManyField(blank=True, null=True, to='api.product')),
            ],
        ),
    ]
