# Generated by Django 4.2.2 on 2023-08-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='passportID',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
