# Generated by Django 4.2.2 on 2023-08-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userprofile_passportid'),
    ]

    operations = [
        migrations.AddField(
            model_name='borderregistration',
            name='subTimeLand',
            field=models.CharField(default='Kenya Airways', max_length=255),
        ),
    ]
