# Generated by Django 4.2.2 on 2023-08-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_subtimeland_borderregistration_subtypeland'),
    ]

    operations = [
        migrations.AddField(
            model_name='borderregistration',
            name='visa',
            field=models.CharField(default='Visa_2Month__$150', max_length=255),
        ),
    ]
