# Generated by Django 4.2.2 on 2023-08-18 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_borderregistration_visa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borderregistration',
            name='idCardNo',
        ),
    ]
