# Generated by Django 4.2.2 on 2023-07-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_userprofile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedFaceDt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageName', models.CharField(max_length=255)),
                ('scannedImage', models.FileField(blank=True, null=True, upload_to='scannedImage/')),
            ],
        ),
    ]
