# Generated by Django 4.2.2 on 2023-07-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='FingerPrintScanDt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerPrintCode', models.TextField()),
                ('fingerPrintImage', models.ImageField(blank=True, null=True, upload_to='scannedFingers/')),
            ],
        ),
    ]
