# Generated by Django 4.2.2 on 2023-07-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_fingerprintscandt_fingerprintimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fingerPrintCode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fingerprintscandt',
            name='fingerPrintCode',
            field=models.TextField(blank=True, null=True),
        ),
    ]
