# Generated by Django 4.2.2 on 2023-08-05 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_userprofile_fingerprintcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='fingerPrintCode',
        ),
    ]
