# Generated by Django 4.2.2 on 2023-08-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_borderregistration_bordercurrentstate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borderregistration',
            name='fingerPrintCD',
        ),
        migrations.AlterField(
            model_name='borderregistration',
            name='borderCurrentState',
            field=models.CharField(choices=[('In', 'In The Country Flight'), ('Out', 'Out The Country')], default='In', max_length=255),
        ),
        migrations.AlterField(
            model_name='borderregistration',
            name='nationality',
            field=models.CharField(choices=[('Somalia', 'Somalia'), ('Somali-Land', 'Somali-Land')], default='Somalia', max_length=255),
        ),
        migrations.AlterField(
            model_name='borderregistration',
            name='userLandedType',
            field=models.CharField(choices=[('By Flight', 'By Flight'), ('By Train', 'By Train'), ('By Bus', 'By Bus')], default='By Flight', max_length=255),
        ),
    ]
