# Generated by Django 4.2.2 on 2023-08-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_borderregistration_fingerprintcd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borderregistration',
            name='userState',
        ),
        migrations.AddField(
            model_name='borderregistration',
            name='reasonFor',
            field=models.CharField(choices=[('Medical', 'Medical'), ('Tourisim', 'Tourisim'), ('Education', 'Education')], default='Education', max_length=255),
        ),
    ]
