# Generated by Django 4.2.2 on 2023-08-12 08:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_borderregistration_userstate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borderregistration',
            name='userProducts',
        ),
        migrations.AlterField(
            model_name='borderregistration',
            name='expireDate',
            field=models.DateTimeField(blank=True, default=api.models.three_month_from_today, null=True),
        ),
        migrations.AlterField(
            model_name='borderregistration',
            name='nationality',
            field=models.CharField(choices=[('Somalia', 'Somalia'), ('Somali-Land', 'Somali-Land'), ('Kenya', 'Kenya '), ('Angola', 'Angola'), ('Italy', 'Italy')], default='Somalia', max_length=255),
        ),
    ]
